// Generated by CoffeeScript 1.10.0
(function() {
  $('document').ready(function() {
    var bodyDivs, hideDivs, selectionTabs, showDiv;
    bodyDivs = $('.bodyDiv');
    selectionTabs = $('.selectionTab');
    hideDivs = function() {
      return bodyDivs.hide();
    };
    showDiv = function(d) {
      hideDivs();
      return bodyDivs.filter("." + d).show();
    };
    showDiv('resumeDiv');
    $('.tabBox').on('click', '.selectionTab', function() {
      console.log("HAH");
      selectionTabs.removeClass('selected');
      $(this).addClass('selected');
      return showDiv($(this).data('tab'));
    });
    return true;
  });

}).call(this);
