// Generated by CoffeeScript 1.10.0
var bodyDivs, tabs;

bodyDivs = document.getElementsByClass('bodyDiv');

hideDivs(function() {
  return bodyDivs.style.display = 'none';
});

showDiv(function(d) {
  return document.getElementsByClass(d).style.display = 'block';
});

hideDivs();

showDiv('resumeDiv');

tabs = document.getElementsByClass('selectionTab');
